### ISSUE TITLE
Inconsistent color rotation during column creation and update

### ISSUE THREAD

**Issue by 9D3F** [brickfield/moodle-mod_board#105]
A possible bug has been investigated in which the colors of the columns in a board do not rotate as expected. 

When opening the board several times, the color sequence remains the same. When creating a new column, the color changes after updating. 

The color of a column is selected from a color array based on its ID. 

![0dd0684e-5b26-4858-80ea-13c5812eabcd](https://github.com/brickfield/moodle-mod_board/assets/114082776/873e82b0-b51b-445c-a48d-bc35046c142e)

When a column is added, the "selectHedaringColour" function is called, which derives the color from the number of columns in the displayed board. This leads to an inconsistent color assignment. 

![6737d959-ab7a-4fb2-a5f6-0314075b5e62](https://github.com/brickfield/moodle-mod_board/assets/114082776/43a2aa1b-897b-4028-b035-00adf453816b)

However, this is only a temporary fix as the real problem lies in the way the colors are defined based on the column count and not the ID. 

A more comprehensive solution would require reworking this logic. When a column is deleted and then a new one is created, the ID continues to be incremented. For example, when the column is added, it initially turns green, but changes to pink after updating. The dark blue column, which should actually be between light blue and pink, is skipped because this is the deleted ID 9.

**Comment by ralfhilg** [comment]
Any progress for this? How can we push the problem?

A teacher will give students exact information and can use the color of a column for orientation specially in class 1-4.

Ie: Add your ideas to the red column.
If the colors are changing this don't make sense?

Shall we provide code for this?

Ralf

**Comment by 9D3F** [comment]
Hi @learningtechnologyservices, 
can one of you contributing to the plugin take on this topic? 

Kind Regards
Dominic

**Comment by learningtechnologyservices** [comment]
Hi Ralf, Dominic,

This is not considered to be a bug by us at Brickfield.

The colours are decorative, and any references to a specific column should always use the column name. For accessibility purposes, a colour alone should never be the sole indicator of meaning, as people can be colour-blind.

The fact that the colours "swap" when being created, versus when being viewed later, they are visual only.

In the case of skipped columns, due to a deleted column, we could look at accepting an integration to fix that one issue, however we have a number of higher priorities to be worked on, at the moment.

Regards
Karen

**Comment by 9D3F** [comment]
Alright understood and many thanks for your response @learningtechnologyservices !

Regards
Dominic
