### ISSUE TITLE
Completion rules missing new suffix

### ISSUE THREAD

**Issue by opitz** [brickfield/moodle-mod_board#109]
From version 4.3 Moodle needs to append a suffix to completion rules (https://moodledev.io/docs/4.3/devupdate#append-a-suffix-to-the-completion-rules).
Missing these results in being removed from the Default activity completion form.

**Comment by learningtechnologyservices** [comment]
Hi Matthias

Many thanks for contributing this essential patch for our completion rules for 4.3, and for the supporting information, and much appreciated that you added the branch check to allow us to use this for our 4.* version!

We'll hopefully get to review and test this next week, so that we can then support 4.3 better going forwards!
