### ISSUE TITLE
error/formsubmissioninvalid when posting content

### ISSUE THREAD

**Issue by simpasami** [brickfield/moodle-mod_board#134]
![image](https://github.com/brickfield/moodle-mod_board/assets/117338882/3f1e0110-92e6-41d4-9ecd-a9119851f714)
Moodle Moodle 4.1.9 (Build: 20240212)
Board 1.401.02 (Build 2022040111)

**Comment by learningtechnologyservices** [comment]
Hi there, this error was fixed in our latest version, 1.401.03, which is available to download via [the Moodle plugins database here](https://moodle.org/plugins/mod_board), or from [our github URL here](https://github.com/brickfield/moodle-mod_board).

Once you have upgraded your Board plugin to this latest version, your workflow should be fine!
