### ISSUE TITLE
feature request: display writer name on post

### ISSUE THREAD

**Issue by Urpokarhu1** [brickfield/moodle-mod_board#25]
Hello,

I would like to see an option in activity settings that would automatically show the name of the person who has posted the message, at the moment no name is shown.

**Comment by learningtechnologyservices** [comment]
HI there,

We understand the request, and if one of our future rounds of funding for the plugin includes the feature we may add it.  

However,  Just like if you were doing a classroom activity with Postit notes - people don't sign them usually.

This was designed to give a student to student anonymous usage by default. No core activity of Moodle has this anonymous contribution aspect so providing something that helped make students comfortable was key!

Teachers can see via the reports to help see who did what and help monitor in case of bad behaviour - however the lack of student names was intentional - for now. 

If you want to help fund more features, get in contact!

Gavin.

**Comment by andreasschenkel** [comment]
@learningtechnologyservices Can you please open this issue again so that I do not have to create a new issue.
I just started to implement this feature. A setting in the board configuration will allow to still create "anonymous" boards so that the users still will not see the autor of a note if the trainer of the course wants this learningsetting.
A note will advise, that the notes are not anonym to the trainer and that the auto of notes might be later set as to be visible.
