### ISSUE TITLE
feature request: attach file to post(.pdf/.doc...)

### ISSUE THREAD

**Issue by mathildemenoret** [brickfield/moodle-mod_board#29]
Hello,
Thanks a lot for this great plugin! In case you are looking for ideas, some teachers I'm working with would appreciate to be able to attach a file and not only a picture to a post. ;-)

**Comment by learningtechnologyservices** [comment]
Hi there Mathilde, one of the issues around adding files to board posts is how would they be displayed and how accessible would they be? 

We have been requested to consider [files such as PDFs as well, and as explained there](https://github.com/brickfield/moodle-mod_board/issues/65), we have included images and links and video links as enabled media items in the board posts, as these are simple to keep accessible. Images have img alt text, and links & video links have descriptive link text (and hopefully the videos themselves have captions too!). Files would require a lot more development work to be able to include them in Board in an accessible way.

As a get-around, you would be able to store your file elsewhere on your Moodle site, within a file resource or forum post for instance, and then use the URL link to link to it instead?

If we receive further funding for Board, we would include this feature for roadmap consideration, but please keep in mind, that we have a number of other features for consideration as well. Hence, at this time we would probably need specific funding for this specific feature, in order to consider it further.
