### ISSUE TITLE
Form issues with too many characters

### ISSUE THREAD

**Issue by cdipe** [brickfield/moodle-mod_board#43]
**Before changing the default number of characters (250)**

- When I could not write more characters, an additional 5-6 characters in the end of the text was lost when saving.
- There was no warning message that there were too many characters.

**After changing to 400 characters**

- Got message that there were more than 400 characters
- When deleting characters and trying to save short message, persistent message about 400 characters.
- Had to reload page to be able to write and save short message.
- Sometimes got message **error/formsubmissioninvalid**

**After changing back to 250 characters**

- Too long text gets truncated in the editor, but no warning message.
- When saving the truncated text, it simply disappears - no new sticky on the board.
- No problem saving short text that has not been truncated.

All this was tested several times, with page reloads inbetween.
Using Moodle 3.11.9 and Board 1.39.06 (Build 2021101501)

**Comment by sehomer** [comment]
Same here, lifting the character limit to 500, entries with about 400 characters are not saved:

error/formsubmissioninvalid

File: /mod/board/external.php (Line 349)

line ? of unknown file: call to mod_board_external:: submit_form()

line 261 pf /lib/externallib.php: call to call_user_func_array()
line 91 of /lib/ajax/service.php: call  to external_api::call_external_ ....

Best regards
Sebastian

**Comment by jojoob** [comment]
The observations from @cdipe are consistent with the code: The `post_max_length` setting is used to put a [length limit on the input field](https://github.com/brickfield/moodle-mod_board/blob/94a12e00e2913a177c90274a02972e8307b2bb5e/classes/note_form.php#L52-L54) and to (silently) [trim the user input](https://github.com/brickfield/moodle-mod_board/blob/03423ce664fc70a4e91814cf8bc371d4d407eadf/classes/board.php#L613) on server side. The [client side Moodle form rule](https://github.com/brickfield/moodle-mod_board/blob/94a12e00e2913a177c90274a02972e8307b2bb5e/classes/note_form.php#L56) is hard coded to 255 characters.

Another problem is that newlines are counted differently. Browsers count code points (browsers send `CR LF` for line breaks and count it as one) while PHP substr() works on bytes (`CR LR` are two bytes). Same applies for all non-ASCII characters. And to make things worse the Moodle form API seems to have an inconsistency between client and server side validation for counting line breaks, see [MDL-76003](https://tracker.moodle.org/browse/MDL-76003) :/

**Comment by cdipe** [comment]
Great! Do you know if there will be a new release with the #46  fix soon?

**Comment by jojoob** [comment]
> Great! Do you know if there will be a new release with the #46 fix soon?

No, but maybe @mchurchward (or @mikechurchward ?) can tell?

**Comment by jojoob** [comment]
Seems e14fcb5a0458f38f361e5c7a26aafe579f4144a3 from Nov 15, 2022 is addressing the issue with the same approach I proposed (sadly without reference - but probably it was developed independently at the same time?). I didn't tested it so far but since the code is nearly the same it should resolve this issue too.

PS: the fix is included in release v1.39.07

**Comment by brickfieldlabs** [comment]
Hi,

We do all the development on an internal system, I can ask one of the team where fixes originate, however since our development system is ahead of the repo here, it may or may not be related to pull requests submitted.

However I will find out.

Regards
Gav.

**Comment by paulffrench** [comment]
Hi,

The first issue regarding the the number of characters a user can add to a posts description not being immediately limited by the global setting for the max character count and this would only come into affect once the post was saved. This would cause any characters that were past the 250 characters point would be removed without warning. This has since been fixed as the user will not be able to input more then the amount specified in the global setting.

Regarding the second issue of receiving the error: error/formsubmissioninvalid. Can you confirm you are using the latest release: 1.xx.xx (Build 2022101201) on your site please and that you can replicate the issue on the latest version?

Kind regards,

Paul

**Comment by cdipe** [comment]
@PaulmFfrench-dev Hi, the characters issue is solved in the version we are using, 1.311.01 (Build 2022101201) in Moodle 3.11.9

But we still sometimes gets the error message error/formsubmissioninvalid, I got it today.

**Comment by paulffrench** [comment]
Hi,

Could you confirm that the error is being caused for yourselves when a posts content contains the maximum number of characters allowed while also containing line breaks? We have a fix coming for the line breaks issue. 

Kind regards,

Paul

**Comment by cdipe** [comment]
@PaulmFfrench-dev I can confirm that. 

- When using all characters, deleting one and adding a line break instead: Got the error message when saving. 
- When using only a few characters and a line break: No error message when saving. 

I repeated this, same result each time.

**Comment by paulffrench** [comment]
Hi,

The upcoming fix should resolve this issue and once it becomes available, could you confirm that it does fix the issue please.

Kind regards,

Paul

**Comment by cdipe** [comment]
Hi @PaulmFfrench-dev 
Yes I can do that when there is a release, I need to upgrade our plugins through the admin interface.

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting second issue of receiving the error: error/formsubmissioninvalid, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/1737ad104f974522bd5eae3738bad3c1ee7763a0). This now correctly allocates and processes the external service parameters for submitting and retrieving posts.

The fix for the line breaks issue is still being reviewed internally.

Kind regards
Karen

**Comment by learningtechnologyservices** [comment]
Hi all,

Many thanks for reporting the line breaks issue generating the error: error/formsubmissioninvalid, we are confident it has been resolved by [this commit 635633a here](https://github.com/brickfield/moodle-mod_board/commit/635633a12f9e41dbbdb19106da2b35a6cc075c7d). This now correctly truncates the content for submitting and retrieving posts.

Kind regards
Karen
