### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by 9D3F** [brickfield/moodle-mod_board#45]
Hi!

Feedback received to date on the use of the Moodle board from teachers and learners across multiple schools with a request for implementation:

- There should be the ability for students to collaborate on the board in real time or near real time updates.

- An alternative activity name of Board (e.g., the German translation "Pinnwand") would be desirable.

- When creating a board, a color picker would be more useful than the standard HEX color code input.

- When selecting background images for boards it would be good to be able to add HEIC files as well.

- The individual definition of the colors of the board columns works so far only limited and in a roundabout way via the website administration settings and then under plugin settings. So far only HEX color codes can be defined, but not selected when creating a board.

- Desirable is also the function to create posts with file attachments.

- A configuration option for the layout of the posts regarding automated height, minimization and fixed height with scrollbars could increase the user friendliness.

- Teachers would like to be able to make the following settings: anonymous participation of all students, names of students only visible to teachers, names of students visible to teachers and students.

Thanks in advance,
ESB

**Comment by learningtechnologyservices** [comment]
Hi Ernst

Many thanks for your many suggestions for our Board plugin! We would always be open to considering features if institutions are willing to fund their development, otherwise we have to prioritise features as we receive funding.

For feedback on your specific suggestions:
1. The Board does update automatically, using the global setting "mod_board | history_refresh". It defaults to 60 seconds so you would be able to ask your admin to speed up the refresh rate.
2. Any Moodle plugin, including Board, can be renamed to [your own customised vocabulary, explained here](https://docs.moodle.org/402/en/Language_customisation). [German translation is fully available here](https://lang.moodle.org/local/amos/view.php?v=401&t=1683558812&l&c=board).
3. Yes, it's on our roadmap to have a color picker.
4. Yes, we're planning to add the option of HEIC images for background.
5. Having per instance column header colours would require development and funding!
6. We have [explained about file attachments on posts here](https://github.com/brickfield/moodle-mod_board/issues/29) and [also here](https://github.com/brickfield/moodle-mod_board/issues/65) 
7. Configuration for layout would be counter-productive to layout responsiveness, which is also very important for user-friend UI.
8. We have explained about [settings for displaying student names here already](https://github.com/brickfield/moodle-mod_board/issues/25), teachers already have full access to view poster names via the reports.

Kind regards
Karen
