### ISSUE TITLE
embedded mod_board 1.400.01 (Build 2022101201) 2022040105 is unusable with Boost theme

### ISSUE THREAD

**Issue by jarvil1** [brickfield/moodle-mod_board#56]
Hello,

Embedded board isn't usable with topics format and Boost theme, it is too narrow and you can't scroll horizontally at all + when you try to add image to a post you can't do it at all, file picker won't open properly.

![image](https://user-images.githubusercontent.com/53904029/225590932-c34a341f-a68d-4dc8-8eeb-5c75e0d32ae8.png)
![boost2](https://user-images.githubusercontent.com/53904029/225590964-a86710d9-c08b-446e-8141-050a8a492d43.png)

https://user-images.githubusercontent.com/53904029/225591187-78e8131c-4211-4b54-8cac-c4319cbd21d7.mp4

**Comment by brickfieldlabs** [comment]
Totally understand, its a feature I wish we would remove as making sure we support different themes, course formats is something we are not paid to do.  We will look into it more.

G

**Comment by jarvil1** [comment]
Hello,

Boost theme and topics format are included in core Moodle

**Comment by brickfieldlabs** [comment]
Yes, we know they are. We will look into making the embed on course page better for topics/boost.

**Comment by christianwolters** [comment]
Hi @brickfieldlabs,

stumbled across this issue, as I am preparing our installations for Moodle 4.x.

I totally get that support for the embed feature is not possible without founding,
and that continued support might prove difficult.

As our users dont have access to this feature, yet (still being on 3.9),
would be willing to provide a simple admin setting controlling the embedability?
(or to accept a PR and release it in the next weeks, respectively?)

Possibly something along this story:

As an administrator,
I want to disable the board embedding feature globally in the admin setting,
in order to prevent board embedding on course pages at all.

Cheers 
Christian

**Comment by brickfieldlabs** [comment]
I believe we have some pending release (and some PR to process), so I agree an admin setting to control embed sounds good.

G.

**Comment by learningtechnologyservices** [comment]
Hi @Urpokarhu1 , returning to this issue report, many thanks for sharing your UX concerns with us.

The board embed width can be edited in the board global settings area, as it's impossible to have a value which will fit all layout possibilities, and we recommend 750px for Topics and Boost.

We can't fix this issue with the file picker easily due to the viewport size, when it's an iframe embedded into the course main page.

Our intention is to remove the ability to add new content to the board when it's embedded, and increase the visibility of the "View board activity" link for users when they want to engage with board content creation.

The embed option was only intended to be a display mechanism only, it's not a good experience otherwise.
