### ISSUE TITLE
Feature request: add PDF to the list of possible attachment types

### ISSUE THREAD

**Issue by nxg** [brickfield/moodle-mod_board#65]
At present, it's possible to attach images to a post, of types BMP, GIF, PNG, and JPG (and of course possible to link to YouTube videos and other external resources).  It would be very useful if the list of attachment types could be expanded to include PDFs.

Use-case: I as a teacher want to post a message saying 'I've noticed an error on p.XXX of the notes, here's an updated version'.  Though I don't use powerpoint myself, I imagine being able to attach something like that would be useful in the same way, so perhaps there's a longer list of useful attachment types.

I don't know how to determine the version of mod_board that's installed in our institutional Moodle, to note it here.

**Comment by learningtechnologyservices** [comment]
Hi there, we have included images and links and video links as enabled media items in the board posts, as these are simple to keep accessible. Images have img alt text, and links & video links have descriptive link text (and hopefully the videos themselves have captions too!). Files would require a lot more development work to be able to include them in Board in an accessible way. 

As a get-around, you would be able to store your file elsewhere on your Moodle site, within a file resource or forum post for instance, and then use the URL link to link to it instead?

If we receive further funding for Board, we would include this feature for roadmap consideration, but please keep in mind, that we have a number of other features for consideration as well. Hence, at this time we would probably need specific funding for this specific feature, in order to consider it further.
