### ISSUE TITLE
Feature request: styling text in posts

### ISSUE THREAD

**Issue by nxg** [brickfield/moodle-mod_board#66]
It would be useful to be able to add basic styling of text in posts.  Markdown would be useful; pulling in something like [MathJax](https://en.wikipedia.org/wiki/MathJax) or [KaTeX](https://en.wikipedia.org/wiki/KaTeX) would be great!

Use-case: I've used [padlet](https://padlet.com/) to support a class for a  couple of years.  Students post questions, possibly including images; I can respond with commentary, explanation, and other notes (sometimes in PDF, see issue/request #65). I'd like to be able to add that commentary/answers, etc readably.

 Padlet is... OK, but is a rather cramped experience, and clumsy for `_emphasis_` or where there's any maths (`x^2+y^2=r^2` or `\cos\theta`).  Padlet have said that they are not interested in adding such formatting (fair enough – I don't think they're really aiming for an educational context), but the lack of this is a standing gripe about padlet amongst my colleagues.  A kanban-like board such as this one helps avoid the sprawling mess that padlet can turn into (and I suspect I'll switch to this just on that ground), but doesn't score any points on the formatting.

I don't know how to determine the version of mod_board that's installed in our institutional Moodle, in order to note it here.

**Comment by learningtechnologyservices** [comment]
Hi Norman,

After reviewing your feature request for styling text in posts, we believe that this configuration, while compelling, would require a significant amount of work, and would bring the Board posts away from the simple "Post-it" style approach it currently encourages. 

However, if we get funding for this in the future, we will consider this improvement.

In the meantime, you could consider emphasis, by means of using the post title, or limited suitable use of all caps, and instead of needing to have maths equations, be able to have a direct descriptive link to a maths equation example being stored or discussed elsewhere, such as forum for instance, within a post.

Many thanks for your feedback on Board!
Karen
