### ISSUE TITLE
Error editing course settings/participants when using board in single activity course

### ISSUE THREAD

**Issue by Flow2702** [brickfield/moodle-mod_board#99]
When using the Board activity as the single activity in a course with single activity course format, after adding the board and configuring it, you loose access to **all** course settings.
Whenever you try to edit these or go to the participants page or try to do anything else in the course menu, following error will occur, rendering the course itself unconfigurable:

> Error: Argument 2 passed to has_capability() must be an instance of context, null given, called in [dirroot]/mod/board/lib.php on line 206

**Comment by Flow2702** [comment]
(Board plugin version is latest: 1.400.01 (Build 2022101201),
Moodle version is  4.1.4 (Build: 20230612))

**Comment by learningtechnologyservices** [comment]
Hi there Flow, many thanks for reporting this situation, our dev team will investigate this shortly!

**Comment by learningtechnologyservices** [comment]
Hi @Flow2702  , we have a [new default 4.1 branch for Board on github](https://github.com/brickfield/moodle-mod_board/tree/MOODLE_401_STABLE), which includes many bug fixes, including for this one.

However, from your version details, it looks like your installation used the MOODLE_400_STABLE branch instead, which does not include most of our bug fixes.

Also, we have been delayed getting this onto the Moodle plugins database, as a new release, due to an issue with 4.2 needing correct event naming (this is also the reason for the CI failures), and our events are currently not following this. We'll see if we can release an up-to-date 4.1 board release in the meantime.

**Comment by learningtechnologyservices** [comment]
Hi @Flow2702 our [new release of Board is now available here](https://moodle.org/plugins/mod_board), which will solve your reported issue! Many thanks!

**Comment by Flow2702** [comment]
Works like a charm now, thank you very much!
